'use client';

import { FormEvent, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronLeft, ChevronRight, CircleCheck } from 'lucide-react';
import { availableCourtCountForWindow, courts, getBookingAvailability, hasContinuousAvailability, type BookingSlot, type Court } from './bookingService';

type Stage = 0 | 1 | 2 | 3 | 4 | 5 | 6;
type CustomerDetails = { name: string; phone: string; email: string; players: string; notes: string };
const initialDetails: CustomerDetails = { name: '', phone: '', email: '', players: '2', notes: '' };

function toDateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function monthKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`; }
function isBeforeToday(date: Date) { const today = new Date(); today.setHours(0, 0, 0, 0); return date < today; }
function getMonthDates(month: Date) { const today = new Date(); today.setHours(0, 0, 0, 0); const first = new Date(month.getFullYear(), month.getMonth(), 1); const start = first.getFullYear() === today.getFullYear() && first.getMonth() === today.getMonth() ? today : first; return Array.from({ length: Math.min(7, new Date(first.getFullYear(), first.getMonth() + 1, 0).getDate() - start.getDate() + 1) }, (_, index) => new Date(start.getFullYear(), start.getMonth(), start.getDate() + index)); }
function dateLabel(key: string, long = false) { const [year, month, day] = key.split('-').map(Number); return new Intl.DateTimeFormat('en-IN', long ? { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' } : { weekday: 'short', day: '2-digit', month: 'short' }).format(new Date(year, month - 1, day)); }
function endTime(time: string, duration: number) { const [clock, suffix] = time.split(' '); const [rawHours, minutes] = clock.split(':').map(Number); const total = (rawHours % 12 + (suffix === 'PM' ? 12 : 0)) * 60 + minutes + duration; const hour = Math.floor((total % 1440) / 60); const displayed = hour % 12 || 12; return `${String(displayed).padStart(2, '0')}:${String(total % 60).padStart(2, '0')} ${hour >= 12 ? 'PM' : 'AM'}`; }

export function BookingExperience() {
  const today = useMemo(() => { const value = new Date(); value.setHours(0, 0, 0, 0); return value; }, []);
  const [stage, setStage] = useState<Stage>(0);
  const [calendarMonth, setCalendarMonth] = useState(new Date(today.getFullYear(), today.getMonth(), 1));
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [selectedDuration, setSelectedDuration] = useState<number>(60);
  const [selectedStartId, setSelectedStartId] = useState<string | null>(null);
  const [selectedCourtId, setSelectedCourtId] = useState<Court['id'] | null>(null);
  const [details, setDetails] = useState<CustomerDetails>(initialDetails);
  const dates = useMemo(() => getMonthDates(calendarMonth), [calendarMonth]);
  const availability = useMemo(() => selectedDate ? getBookingAvailability(selectedDate) : null, [selectedDate]);
  const timeOptions = availability?.['court-1'] ?? [];
  const selectedCourt = courts.find((court) => court.id === selectedCourtId) ?? null;
  const selectedSlot = selectedCourt && selectedStartId && availability ? availability[selectedCourt.id].find((slot) => slot.id === selectedStartId) ?? null : null;
  const bookingPrice = selectedSlot ? Math.round(selectedSlot.price * selectedDuration / 60) : 0;
  const activeStep = stage < 2 ? 1 : stage === 2 ? 2 : stage === 3 ? 3 : 4;

  function chooseDate(date: Date) { setSelectedDate(toDateKey(date)); setSelectedStartId(null); setSelectedCourtId(null); setStage(2); }
  function chooseDuration(duration: number) { setSelectedDuration(duration); setSelectedStartId(null); setSelectedCourtId(null); }
  function chooseTime(slot: BookingSlot) { if (!availability || availableCourtCountForWindow(availability, slot.id, selectedDuration) === 0) return; setSelectedStartId(slot.id); setSelectedCourtId(null); setStage(3); }
  function chooseCourt(courtId: Court['id']) { setSelectedCourtId(courtId); setStage(4); }
  function changeMonth(delta: number) { const next = new Date(calendarMonth.getFullYear(), calendarMonth.getMonth() + delta, 1); if (!isBeforeToday(new Date(next.getFullYear(), next.getMonth() + 1, 0))) setCalendarMonth(next); }
  function selectMonth(value: string) { if (!value) return; const next = new Date(`${value}-01T12:00:00`); if (!isBeforeToday(new Date(next.getFullYear(), next.getMonth() + 1, 0))) setCalendarMonth(next); }
  function confirmBooking(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStage(6); }
  const back = stage === 2 ? () => setStage(1) : stage === 3 ? () => setStage(2) : stage === 4 ? () => setStage(3) : stage === 5 ? () => setStage(4) : () => undefined;

  return <section className="booking-main booking-experience section" id="booking-form" aria-labelledby="booking-title">
    {stage === 0 ? <div className="booking-landing"><div><div className="section-kicker"><span>A</span><p>Book a court</p><i /></div><h2 id="booking-title">YOUR NEXT<br />GAME STARTS <em>HERE.</em></h2></div><div className="booking-landing-action"><p>Choose your date, duration and start time. We’ll show the courts that are free for the entire booking.</p><button type="button" className="booking-primary-action" onClick={() => setStage(1)}>Book a court <ArrowRight size={18} /></button></div></div> : <div className="booking-flow" id="booking-flow">
      <ol className="booking-stepper" aria-label="Booking progress">{['Date', 'Time', 'Court', 'Confirm'].map((label, index) => { const step = index + 1; const complete = activeStep > step; return <li key={label} className={activeStep === step ? 'is-active' : complete ? 'is-complete' : ''}><span>{complete ? <Check size={14} strokeWidth={3} /> : `0${step}`}</span><b>{label}</b></li>; })}</ol>
      <div className="booking-single-panel">
        {stage >= 2 && stage <= 5 && <button className="booking-back" type="button" onClick={back}><ArrowLeft size={16} /> Back</button>}
        {stage === 1 && <section className="booking-step-panel" aria-labelledby="booking-date-title"><div className="booking-step-heading"><p>Step 01</p><h3 id="booking-date-title">Select your date</h3><span>Choose any future month, then select your day.</span></div><div className="booking-date-toolbar"><button type="button" onClick={() => changeMonth(-1)} disabled={monthKey(calendarMonth) === monthKey(today)}><ChevronLeft size={16} /> Previous</button><label className="booking-month-picker">Month <input type="month" min={monthKey(today)} value={monthKey(calendarMonth)} onChange={(event) => selectMonth(event.target.value)} /></label><button type="button" onClick={() => changeMonth(1)}>Next <ChevronRight size={16} /></button></div><div className="booking-date-list" role="list">{dates.map((date) => { const key = toDateKey(date); return <button key={key} type="button" role="listitem" className={selectedDate === key ? 'is-selected' : ''} aria-pressed={selectedDate === key} onClick={() => chooseDate(date)}><span>{new Intl.DateTimeFormat('en-IN', { weekday: 'short' }).format(date)}</span><strong>{String(date.getDate()).padStart(2, '0')}</strong><small>{new Intl.DateTimeFormat('en-IN', { month: 'short' }).format(date)}</small></button>; })}</div></section>}
        {stage === 2 && availability && <section className="booking-step-panel booking-time-panel" aria-labelledby="booking-time-title"><div className="booking-step-heading"><p>Step 02</p><h3 id="booking-time-title">Choose time &amp; duration</h3><span>{dateLabel(selectedDate!, true)} · Select a continuous booking window.</span></div><div className="booking-duration-slider"><div><span>Booking duration</span><strong>{selectedDuration} <small>minutes</small></strong></div><input type="range" min="30" max="180" step="30" value={selectedDuration} aria-valuemin={30} aria-valuemax={180} aria-valuenow={selectedDuration} aria-valuetext={`${selectedDuration} minutes`} onChange={(event) => chooseDuration(Number(event.target.value))} /><div className="booking-duration-scale" aria-hidden="true"><span>30 min</span><span>90 min</span><span>180 min</span></div></div>{(['Morning', 'Afternoon', 'Evening'] as const).map((period) => <div className="booking-slot-group" key={period}><h4>{period}</h4><div className="booking-slot-grid">{timeOptions.filter((slot) => slot.period === period).map((slot) => { const availableCourts = availableCourtCountForWindow(availability, slot.id, selectedDuration); return <button type="button" key={slot.id} disabled={availableCourts === 0} className={`booking-slot ${availableCourts === 0 ? 'is-unavailable' : ''}`} onClick={() => chooseTime(slot)}><strong>{slot.time}</strong><span>until {endTime(slot.time, selectedDuration)}</span><small>{availableCourts ? `${availableCourts} court${availableCourts > 1 ? 's' : ''} free` : 'Unavailable'}</small></button>; })}</div></div>)}</section>}
        {stage === 3 && availability && selectedStartId && <section className="booking-step-panel booking-court-panel" aria-labelledby="booking-court-title"><div className="booking-step-heading"><p>Step 03</p><h3 id="booking-court-title">Available courts</h3><span>{dateLabel(selectedDate!, true)} · {timeOptions.find((slot) => slot.id === selectedStartId)?.time} – {endTime(timeOptions.find((slot) => slot.id === selectedStartId)?.time ?? '06:00 AM', selectedDuration)} · {selectedDuration} minutes</span></div><div className="booking-court-grid">{courts.map((court) => { const isAvailable = hasContinuousAvailability(availability[court.id], selectedStartId, selectedDuration); return <button type="button" key={court.id} className={`booking-court-card ${!isAvailable ? 'is-sold-out' : ''}`} disabled={!isAvailable} onClick={() => chooseCourt(court.id)}><span className="booking-court-number">{court.number}</span><strong>{court.name}</strong><small>{court.type}</small><p>{isAvailable ? `Free for ${selectedDuration} minutes` : 'Not available'}</p><em>{isAvailable ? 'Book this court' : 'Try another time'} <ArrowRight size={14} /></em></button>; })}</div></section>}
        {stage === 4 && selectedSlot && selectedCourt && <section className="booking-step-panel booking-review-panel" aria-labelledby="booking-review-title"><div className="booking-step-heading"><p>Step 04</p><h3 id="booking-review-title">Your booking</h3><span>Review your court before we take your details.</span></div><div className="booking-review"><div><span>Date</span><strong>{dateLabel(selectedDate!, true)}</strong></div><div><span>Court</span><strong>{selectedCourt.name}</strong></div><div><span>Time</span><strong>{selectedSlot.time} – {endTime(selectedSlot.time, selectedDuration)}</strong></div><div><span>Duration &amp; price</span><strong>{selectedDuration} min · ₹{bookingPrice}</strong></div></div><button type="button" className="booking-primary-action" onClick={() => setStage(5)}>Continue to booking <ArrowRight size={18} /></button></section>}
        {stage === 5 && selectedSlot && selectedCourt && <section className="booking-step-panel booking-details-panel" aria-labelledby="booking-details-title"><div className="booking-step-heading"><p>Step 05</p><h3 id="booking-details-title">Your details</h3><span>Just what we need to confirm your court.</span></div><form onSubmit={confirmBooking} className="booking-details-form"><label>Name<input required autoComplete="name" value={details.name} onChange={(event) => setDetails({ ...details, name: event.target.value })} /></label><label>Phone number<input required type="tel" autoComplete="tel" value={details.phone} onChange={(event) => setDetails({ ...details, phone: event.target.value })} /></label><label>Email<input required type="email" autoComplete="email" value={details.email} onChange={(event) => setDetails({ ...details, email: event.target.value })} /></label><label>Number of players<select value={details.players} onChange={(event) => setDetails({ ...details, players: event.target.value })}><option value="1">1 player</option><option value="2">2 players</option><option value="3">3 players</option><option value="4">4 players</option></select></label><label className="booking-notes">Notes <span>(optional)</span><textarea rows={3} value={details.notes} onChange={(event) => setDetails({ ...details, notes: event.target.value })} /></label><button className="booking-primary-action" type="submit">Confirm booking <ArrowRight size={18} /></button></form></section>}
        {stage === 6 && selectedSlot && selectedCourt && <section id="booking-confirmed" className="booking-confirmed booking-step-panel"><CircleCheck size={42} /><p>Booking confirmed</p><strong>Your court is ready.</strong><span>{selectedCourt.name} · {dateLabel(selectedDate!, true)} · {selectedSlot.time} – {endTime(selectedSlot.time, selectedDuration)}</span><span>Booking ID · TPC-{selectedDate?.replaceAll('-', '')}-{selectedCourt.number}</span><a href="/">Back to home <ArrowRight size={15} /></a></section>}
      </div>
    </div>}
  </section>;
}
